### ISSUE TITLE
Milestone #3 - Feedback Priorities 

### ISSUE THREAD

**Issue by sweber15** [UBC-MDS/DSCI532_GROUP104_Movies#69]
Priority 1:
- [ ]  Re-write text at the top of the app to make the purpose more clear

- [ ] Remove "This app is for you" to simplify the 

- [ ] Add a description on the relationship between filtering in the bar chart and the effects on the line chart

- [ ]  Make "Shift + Click" clear to users to filter multiple directors

Priority 2:
- [ ]  Change colour of the instructions to make them stand out more from the header. 

- [ ] Look into changing layout as one computer had a scroll bar while others did not. 

- [ ] Make points bigger in the line charts to improve readability

- [ ] Put a cap on the number of directors that can be selected

- [ ]  If there is less than 30 directors in a genre then update 30 in the title with the count of directors. 

In-Progress, unknown timeline:

- [ ] The initial load screen has all the directors selected, but we cannot filter upon loading to make the line charts not as crowded. 

README updates: 

- [ ]  Add that movies can only be in one genre at a time to address confusions on if categories overlap.
